import localFont from "next/font/local";
import "./globals.css";
import Navbar from '../components/Navbar';
import TranslationProvider from '../components/TranslationProvider'; // استدعاء مكون الترجمة
import Footer from '../components/Footer'; // استدعاء الفوتر

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <TranslationProvider>
      <body className="flex flex-col min-h-screen">
        <Navbar />
        <main className="flex-grow">{children}</main> {/* إضافة flex-grow لضمان الامتداد */}
        <Footer />
      </body>
    </TranslationProvider>
  );
}
